server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080/identity
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081/profile
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: file_service
          uri: http://localhost:8083/file
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8084/product
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2