server:
  port: 8084
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAMEDB}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: product_service_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB

genai:
  api-key: ${GEMINI_API}

removebg:
  api-key: ${REMOVEBG_API_KEY:}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-2
aws:
    s3:
      bucket: ${BUCKET}